import { randomUUID } from "crypto";

export const JOBS = [
    {
        id: randomUUID(),
        logo: "/logos/scoot.svg", // imágenes en public/logos/
        logoBg: "#E99210",
        postedAt: "5h ago",
        contractType: "Full Time",
        position: "Senior Software Engineer",
        company: "Scoot",
        location: "United Kingdom",
    },
    {
        id: randomUUID(),
        logo: "/logos/blogr.svg",
        logoBg: "#E54D2E",
        postedAt: "20h ago",
        contractType: "Freelance",
        position: "Haskell Developer",
        company: "Blogr",
        location: "United States",
    },
    {
        id: randomUUID(),
        logo: "/logos/vector.svg",
        logoBg: "#2F4FCB",
        postedAt: "1d ago",
        contractType: "Part Time",
        position: "Frontend Developer",
        company: "Vector",
        location: "Germany",
    },
    {
        id: randomUUID(),
        logo: "/logos/officelite.svg",
        logoBg: "#3DBFF8",
        postedAt: "2d ago",
        contractType: "Full Time",
        position: "UX/UI Designer",
        company: "OfficeLite",
        location: "Canada",
    },
    {
        id: randomUUID(),
        logo: "/logos/pod.svg",
        logoBg: "#F16718",
        postedAt: "3d ago",
        contractType: "Contract",
        position: "DevOps Engineer",
        company: "Pod",
        location: "Australia",
    },
    {
        id: randomUUID(),
        logo: "/logos/maker.svg",
        logoBg: "#2146C7",
        postedAt: "4d ago",
        contractType: "Full Time",
        position: "Backend Developer",
        company: "Maker",
        location: "United States",
    },
    {
        id: randomUUID(),
        logo: "/logos/coffee.svg",
        logoBg: "#A47C48",
        postedAt: "1w ago",
        contractType: "Freelance",
        position: "React Developer",
        company: "Coffee Co.",
        location: "Brazil",
    },
    {
        id: randomUUID(),
        logo: "/logos/cloud.svg",
        logoBg: "#0EA5E9",
        postedAt: "1w ago",
        contractType: "Full Time",
        position: "Cloud Architect",
        company: "SkyCloud",
        location: "Spain",
    },
    {
        id: randomUUID(),
        logo: "/logos/neo.svg",
        logoBg: "#901bcf",
        postedAt: "2w ago",
        contractType: "Full Time",
        position: "Fullstack Developer",
        company: "NeoTech",
        location: "Netherlands",
    },
    {
        id: randomUUID(),
        logo: "/logos/green.svg",
        logoBg: "#16A34A",
        postedAt: "2w ago",
        contractType: "Part Time",
        position: "QA Engineer",
        company: "GreenSoft",
        location: "Chile",
    },
    {
        id: randomUUID(),
        logo: "/logos/byte.svg",
        logoBg: "#7C3AED",
        postedAt: "3w ago",
        contractType: "Contract",
        position: "Mobile Developer",
        company: "ByteLabs",
        location: "Mexico",
    },
    {
        id: randomUUID(),
        logo: "/logos/alpha.svg",
        logoBg: "#DC2626",
        postedAt: "3w ago",
        contractType: "Full Time",
        position: "Data Engineer",
        company: "Alpha Data",
        location: "Argentina",
    },
    {
        id: randomUUID(),
        logo: "/logos/zen.svg",
        logoBg: "#059669",
        postedAt: "1mo ago",
        contractType: "Freelance",
        position: "Node.js Developer",
        company: "ZenCode",
        location: "Japan",
    },
    {
        id: randomUUID(),
        logo: "/logos/rocket.svg",
        logoBg: "#F43F5E",
        postedAt: "1mo ago",
        contractType: "Full Time",
        position: "Tech Lead",
        company: "Rocket Labs",
        location: "United Kingdom",
    },
    {
        id: randomUUID(),
        logo: "/logos/logic.svg",
        logoBg: "#ffcd64",
        postedAt: "1mo ago",
        contractType: "Contract",
        position: "System Architect",
        company: "LogicWorks",
        location: "United States",
    },
    {
        id: randomUUID(),
        logo: "/logos/pixel.svg",
        logoBg: "#9333EA",
        postedAt: "2mo ago",
        contractType: "Full Time",
        position: "Vue.js Developer",
        company: "Pixel Studio",
        location: "France",
    },
    {
        id: randomUUID(),
        logo: "/logos/core.svg",
        logoBg: "#273759",
        postedAt: "2mo ago",
        contractType: "Full Time",
        position: "Java Developer",
        company: "Core Systems",
        location: "Germany",
    },
    {
        id: randomUUID(),
        logo: "/logos/nimbus.svg",
        logoBg: "#38BDF8",
        postedAt: "2mo ago",
        contractType: "Freelance",
        position: "Python Developer",
        company: "Nimbus",
        location: "India",
    },
    {
        id: randomUUID(),
        logo: "/logos/forge.svg",
        logoBg: "#B91C1C",
        postedAt: "3mo ago",
        contractType: "Full Time",
        position: "Security Engineer",
        company: "ForgeSec",
        location: "Israel",
    },
    {
        id: randomUUID(),
        logo: "/logos/atlas.svg",
        logoBg: "#1E293B",
        postedAt: "3mo ago",
        contractType: "Contract",
        position: "Site Reliability Engineer",
        company: "Atlas Corp",
        location: "Sweden",
    },
    {
        id: randomUUID(),
        logo: "/logos/lumen.svg",
        logoBg: "#F59E0B",
        postedAt: "3mo ago",
        contractType: "Full Time",
        position: "Product Engineer",
        company: "Lumen",
        location: "Italy",
    },
    {
        id: randomUUID(),
        logo: "/logos/horizon.svg",
        logoBg: "#14B8A6",
        postedAt: "4mo ago",
        contractType: "Part Time",
        position: "Scrum Master",
        company: "Horizon Tech",
        location: "Portugal",
    },
    {
        id: randomUUID(),
        logo: "/logos/delta.svg",
        logoBg: "#6366F1",
        postedAt: "4mo ago",
        contractType: "Full Time",
        position: "Angular Developer",
        company: "Delta Solutions",
        location: "Poland",
    },
    {
        id: randomUUID(),
        logo: "/logos/spark.svg",
        logoBg: "#F97316",
        postedAt: "4mo ago",
        contractType: "Freelance",
        position: "AI Engineer",
        company: "Spark AI",
        location: "South Korea",
    },
    {
        id: randomUUID(),
        logo: "/logos/quantum.svg",
        logoBg: "#0EA5E9",
        postedAt: "5mo ago",
        contractType: "Full Time",
        position: "Machine Learning Engineer",
        company: "Quantum Labs",
        location: "Singapore",
    },
    {
        id: randomUUID(),
        logo: "/logos/bridge.svg",
        logoBg: "#4B5563",
        postedAt: "5mo ago",
        contractType: "Contract",
        position: "Blockchain Developer",
        company: "BridgeChain",
        location: "Switzerland",
    },
    {
        id: randomUUID(),
        logo: "/logos/aurora.svg",
        logoBg: "#DB2777",
        postedAt: "6mo ago",
        contractType: "Full Time",
        position: "Engineering Manager",
        company: "Aurora Tech",
        location: "Norway",
    },
];
